### ISSUE TITLE
Issues on all Operating Systems

### ISSUE THREAD

**Issue by nottinhill** [imagemin/imagemin#152]
can be deleted.

**Comment by shinnn** [comment]
@nottinhill Even if you've edited the issue description, thanks to the [Github user event API](https://developer.github.com/v3/activity/events/#list-events-performed-by-a-user), we can easily see what you initially wrote.

[events.json.txt](https://github.com/imagemin/imagemin/files/122064/events.json.txt)

> Imagemin is by the far the Project that causes us the most headaches. Lots of unresolved dependencies, proxy issues, versions, you name it imagemin has it. Am I the only one?

First of all, thanks for using imagemin! I'm always proud to maintain this project, used by a lot of developers all over the world. Also, I'm glad to receive your love letter with such a too much love.

Next time please file an issue with more detailed information, for example your platform, Node/npm/imagemin versions, full stack trace, and example code/repository.

Moreover, because imagemin is an open source project, everyone has a chance to submit a patch to fix or improve it. Actually, the tools I'm currently using for web development were not always just what I wanted. I've read the code, discussed the authors and created pull requests to make them close to what I want.

Let's make the Web a little faster by better image minification, @nottinhill.
