### ISSUE TITLE
/node_modules/jpegtran-bin/vendor/jpegtran ENOENT

### ISSUE THREAD

**Issue by jeroenb2511** [imagemin/imagemin#154]
What do I wrong?

Node 5.6.0
NPM 3.7.2
imagemin 2.4.0

events.js:154
      throw er; // Unhandled 'error' event
      ^
Error: spawn /Users/jeroen/Documents/Development/Suz/node_modules/jpegtran-bin/vendor/jpegtran ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:475:9)
    at process._tickCallback (node.js:389:17)

**Comment by shinnn** [comment]
* Which OS?
* Is there any error messages while installing?

**Comment by jeroenb2511** [comment]
OSX, 10.11.3 (El Capitan)
No error messages when I installed, only when I am running the gulp task.

**Comment by shinnn** [comment]
* Is the binary is actually installed in `/Users/jeroen/Documents/Development/Suz/node_modules/jpegtran-bin/vendor/jpegtran`?
  * `ls /Users/jeroen/Documents/Development/Suz/node_modules/jpegtran-bin/vendor/`
* Is your network under some kind of proxies?

**Comment by jeroenb2511** [comment]
Hmm, strange. I think you will close this issue, because after an reinstall of the npm install (first removed node_modules) it works ok. I found the vendor binary in the node_modules ;)

**Comment by shinnn** [comment]
@jeroenb2511 Glad to hear that :)

**Comment by aakankshkarma** [comment]
Hi

I currently have same issue with following error

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: spawn /home/vagrant/Projects/qs/wp-content/themes/qs/node_modules/jpegtran-bin/vendor/jpegtran ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by kevva** [comment]
Does `jpegtran` exist at `/home/vagrant/Projects/qs/wp-content/themes/qs/node_modules/jpegtran-bin/vendor/`? If not, it probably failed to install.

**Comment by discordianfish** [comment]
Same issue. If this fails to install, shouldn't the whole npm package install fail? It didn't in my case.

**Comment by trompx** [comment]
Same error, and the jpegtran-bin/vendor/jpegtran file exists.
I tried removing node_modules and reinstalling with npm and yarn but still getting the error.
Not a permission problem either.

My setup:
```
OS: Alpine 3.6
Yarn: 0.27.5
Npm: 3.10.2
Node: 6.10.3
```

**Comment by mbajur** [comment]
I have exactly the same issue, the binary is in place and my setup is:

```
OS: Alpine 2.4.2
Yarn: 1.1.0
Node: 8.6.0
```

This issue should definitely be opened :)

**Comment by mbajur** [comment]
Ok, it turned out to be caused by a fact that i had not `libjpeg-turbo libjpeg-turbo-dev libpng libpng-dev` packages installed. After apk-adding them, gulp-imagemin started to work.

**Comment by discordianfish** [comment]
To be clear: There isn;t anything imagemin can do if jpegtran can't be build and the vendored one doesn't fit the platform. But IMO it should failr if it can't build.

**Comment by krolovolk** [comment]
@mbajur did you try to install jpegtran-bin from npm?
`npm install --save jpegtran-bin`

**Comment by CarlosTenorio** [comment]
Try to rebuild the jpegtran-bin package.
`npm rebuild jpegtran-bin`

**Comment by jc1dev** [comment]
why is issue closed when it's still a problem?

**Comment by jamietanna** [comment]
Digging into this:

```
/app/site # node -v
v8.9.3
/app/site # npm -v
5.5.1
/app/site # cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.7.0
PRETTY_NAME="Alpine Linux v3.7"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
```

```
/app/site # ls -al /app/node_modules/jpegtran-bin/vendor/jpegtran
-rwxr-xr-x    1 root     root        306001 Apr  8 17:01 /app/node_modules/jpegtran-bin/vendor/jpegtran
/app/site # file /app/node_modules/jpegtran-bin/vendor/jpegtran
/app/node_modules/jpegtran-bin/vendor/jpegtran: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.26, BuildID[sha1]=3c217e25804f600bdae67c2db9cac2108e32ccef, not stripped
/app/site # /app/node_modules/jpegtran-bin/vendor/jpegtran
sh: /app/node_modules/jpegtran-bin/vendor/jpegtran: not found
```

The issue seems to be the linking against `/lib64/ld-linux-x86-64.so.2`, which does not exist on Alpine:

```
/app/site # ls -al /lib64/ld-linux-x86-64.so.2
ls: /lib64/ld-linux-x86-64.so.2: No such file or directory
```

When installing the alpine package `libjpeg-turbo-utils`, we can see the system `jpegtran` is linked correctly:

```
/app/site # file /usr/bin/jpegtran
/usr/bin/jpegtran: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, stripped
```

I've found that a workaround is to force the system `jpegtran` over the one bundled in the NPM package:

```
/app/site # ln -sf /usr/bin/jpegtran /app/node_modules/jpegtran-bin/vendor/jpegtran
/app/site # gulp imagemin
[17:46:44] Using gulpfile /app/site/gulpfile.js
[17:46:44] Starting 'imagemin'...
[17:47:34] gulp-imagemin: Minified n images
[17:47:34] Finished 'imagemin' after 50 s
```

**Comment by eltiare** [comment]
None of the solutions worked for me, am on the node:alpine docker image. :(

**Comment by adamreisnz** [comment]
Reinstall packages with clearing node modules cache worked for me to tackle this issue on Heroku

**Comment by YewTreeWeb** [comment]
> Try to rebuild the jpegtran-bin package.
> `npm rebuild jpegtran-bin`

This worked for me when having the same issue.

**Comment by lreece** [comment]
Thank you. I looked (on my Windows machine) for the /vendor/ directory (in /jpegtran-bin/) and it wasn't there, so I manually installed the modules it was looking for (jpegtran-bin and optipng-bin in my case), and it finally worked for me.

**Comment by teacherpan** [comment]
> Thank you. I looked (on my Windows machine) for the /vendor/ directory (in /jpegtran-bin/) and it wasn't there, so I manually installed the modules it was looking for (jpegtran-bin and optipng-bin in my case), and it finally worked for me.

FIXED!

**Comment by kuloyants** [comment]
> Try to rebuild the jpegtran-bin package.
> `npm rebuild jpegtran-bin`

That worked for me. Thanks!

**Comment by aqabawe** [comment]
Yarn doesn't have version 3.4, that's why the package wasn't downloading in our case.

**Comment by jnaklaas** [comment]
Yarn has no rebuild, but you could `npm rebuild jpegtran-bin --update-binary` which doesn't change the package.lock so should not interfere with yarn.

**Comment by nwallace** [comment]
> None of the solutions worked for me, am on the node:alpine docker image. :(

I figured out my issue using the node:alpine Docker image: **add the package `libc6-compat`**, in addition to the other previously mentioned dependencies:

```
RUN apk add --no-cache --update build-base libpng-dev libjpeg-turbo-dev libc6-compat
```

Here's how I figured that out, in case that doesn't exactly work for someone else:

1. Edit my Dockerfile to install the node modules, but stop before it actually runs `jpegtran` (in my case, via `gulp build`)
2. Run and attach to the resulting container to debug the issue
3. From the error message, it's clear that it's failing to run the `jpegtran` binary. Try to run that inside the container manually, but got an error "Command not found" (or something close to that). Don't understand because I can see the file, it's marked executable, looks otherwise okay.
4. Learn from [this SO question](https://stackoverflow.com/questions/35071872/bash-no-such-file-or-directory) that it's likely a missing dynamic linker.
5. In container, run `readelf --all ./node_modules/jpegtran-bin/vendor/jpegtran | grep interpreter`. Okay, it's looking for `/lib64/ld-linux-x86-64.so.2`. That file doesn't exist in the container.
6. Search for [packages that provide that file](https://pkgs.alpinelinux.org/contents?file=ld-linux-x86-64.so.2) on Alpine's website. Learn that there are two providers: `gcompat` and `libc6-compat`.
7. Tried `gcompat` first, but it only installed /lib/ld-linux-x86-64.so.2, not /lib**64**/ld-linux-x86-64.so.2. `libc6-compat` did.
8. Re-run `jpegtran` manually, it works this time

**Comment by lekkerduidelijk** [comment]
@nwallace You saved me from going bald after pulling my hair for the last 4 hours. Thanks a bunch! 🥳 

We use a custom docker image based on alpine:3.9 with Ansible, Yarn and Node. moz-jpeg is giving us issues for a couple of years now going back and forth.

The RUN command looks like this now:
```dockerfile
RUN apk add --no-cache python3 curl nodejs yarn build-base libpng-dev libjpeg-turbo-dev libc6-compat
```
