### ISSUE TITLE
API use vs. plugins options

### ISSUE THREAD

**Issue by thisconnect** [imagemin/imagemin#176]
The imagemin readme describes the option "plugins" (Array of plugins to use.)

Some imagemin plugins docs mention "use" which is not mentioned in the imagemin readme. Is "use" and "plugins" the same?
(e.g. https://github.com/imagemin/imagemin-jpegtran)

Other plugins use chaining and the "use" method is this the same as "plugins" or "use" option?
https://github.com/imagemin/imagemin-pngout

**Comment by kevva** [comment]
Yes, we initially used the name `use` but changed it to `plugins`. We're still aliasing `use` for backwards compatibility (see https://github.com/imagemin/imagemin/blob/master/index.js#L48), but it'll be deprecated in the feature.

`imagemin-pngout` can't be used with the new API yet since it's not converted yet, though that'll be on my list of things to fix very soon.

**Comment by thisconnect** [comment]
Thanks
