### ISSUE TITLE
CLI doesn't seem to work as npm script

### ISSUE THREAD

**Issue by jmeas** [imagemin/imagemin#185]
The script seems to immediately complete if run as an npm script. Steps to reproduce:

1. install imagemin-cli locally for an npm project
2. set up an npm script that runs `imagemin <something>`
3. run your script

You should observe that the script resolves instantly, and that the output file has a size of 0kb.

I should note that I was using the pngquant plugin in my example, which could be relevant.

This was using the latest release of imagemin-cli, 3.0.0

**Comment by shinnn** [comment]
I cannot reproduce the problem.

```json
"scripts": {
    "imagemin": "imagemin fixture.jpg --out-dir dest"
}
```

[./fixture.jpg](https://c1.staticflickr.com/9/8735/27667671133_3ec1f12d82_m.jpg)

```
$ sw_vers
> ProductName:	Mac OS X
> ProductVersion:	10.11.5
> BuildVersion:	15F34
$ node- v
> v6.3.0
$ npm -v
> 3.10.5
$ npm ls imagemin-cli
> test@1.0.0 /Users/shinnn/github/test
> └── imagemin-cli@3.0.0  extraneous
$ npm run imagemin --silent
> 1 image minified
$ ls -l fixture.jpg dest/fixture.jpg
> -rw-r--r--  1 shinnn  staff  13603  7 13 21:53 dest/fixture.jpg
> -rw-r--r--@ 1 shinnn  staff  14211  7 13 21:44 fixture.jpg
```

npm script just works fine.

**Comment by jmeas** [comment]
Interesting! Thanks for checking. I'll set up a repo to try and demonstrate it.

**Comment by jmeas** [comment]
@shinnn , I tried reproducing it in a separate repo, but couldn't. I then went back to the original project I was having the issue in, and was able to reproduce it.

I opened [a PR in the repo](https://github.com/jmeas/moolah/pull/375) – instructions for reproducing are there, too (they are short).

If you get a chance to try this out, let me know if you see the same behavior.

**Comment by shinnn** [comment]
Okey, I found the cause.

This is a good example command that fully explains why a 0 byte file is always created:

```
cat foo > foo
```

When `foo` doesn't exit, `cat foo` shows the `No such file or directory` error. But the command above doesn't shows the error and it successfully writes a file to `./foo`. That means, when you run a command `xxx > yyy`,
 
1. First, a temporary 0 byte file will be written in `yyy`.
2. Second, the command `xxx` will be evaluated. If you try to read `yyy` inside `xxx` command, it results in a 0 byte data because at this time `yyy` is **already empty**. 👻
