### ISSUE TITLE
Benchmarks?

### ISSUE THREAD

**Issue by corysimmons** [imagemin/imagemin#219]
I've been using imagemin for a while just because of the devs around it, but does anyone have any stats on how it stacks up to other image minifiers? A co-worker is suggesting ImageAlpha and ImageOptim.

If not, could someone write a blog post on this or add a cool graph to the README?

**Comment by hatzopoulos** [comment]
ImageAlpha is a GUI for png only and uses pngquant, pngnq and posterizer

ImageOptim is another GUI which under the hood uses PNGOUT, AdvPNG, Pngcrush, OptiPNG, JpegOptim, MozJPEG, jpegtran, and Gifsicle

The only plugin I don't see for imagemin is pngnq and posterizer and I don't think that really matters with the 5 other png plugins available. So they all pretty much use the same open source compressors, and imagemin has the better coverage IMO as seen on https://www.npmjs.com/browse/keyword/imageminplugin

**Comment by corysimmons** [comment]
Thanks for the info. I figured the GUIs were probably using open-source compressors under the hood.

I've been lazily using [imagemin-cli's defaults](https://github.com/imagemin/imagemin-cli/blob/master/cli.js#L37-L42).

Co-workers are claiming these "stacks" offer significantly higher compression than imagemin-cli's defaults:

- png: `ImageAlpha -> ImageOptim` (co-worker claims to have shrank 700kb to 100kb which wow'd my socks off)
- jpg: `JPGmini -> ImageOptim`

I'll do a few of my own tests on various images and post my results this weekend, but if there are huge savings to be had by combining various compressors it might be a worthy endeavor to create some sort of engine that would test various combinations of these plugins to get huge, near-lossless savings.

**Comment by stevendesu** [comment]
Imagemin is just a light wrapper around multiple different image optimization tools:

https://www.npmjs.com/browse/keyword/imageminplugin

You'd need to look into benchmarks for the different tools. I don't have any numbers in front of me, but from some limited research a year ago I recall pngquant being the best tool for PNGs. I also did some tests about a week ago and found mozjpeg was the best for JPEG files (~30% smaller than all other tools I tested) although that may be a special case for the files I was optimizing.

Also whenever you hear large stats like a file shrinking from 700kb to 100kb, it's good to investigate and see what's going on. Maybe the 700kb file was the least-optimized possible bitmap and any minification tool would have gotten it around ~100kb. Maybe one of the tools he used was lossy and destroyed the quality. Maybe one of the tools was limiting the image size (in pixels) -- I usually run a gulp script which limits my images to 1600px wide because anything wider than this is just overkill in my opinion.

**Comment by corysimmons** [comment]
Thanks @stevendesu 

I'll revisit this in the future. I think I'd like to combine https://github.com/uber/image-diff/ with imagemin and just throw a million combinations at it so quality is >= 90% with the most savings.

It'd take a while to process a directory of images using various settings, so I'll just use imagemin defaults and wrap that functionality up into a package to run as a build step. Then run that step overnight or something.

I'll record the winning combinations, and if I end up noticing a particular combination routinely does better I can report back.
