### ISSUE TITLE
Images don't load on iOS Safari

### ISSUE THREAD

**Issue by Sunhat** [imagemin/imagemin#301]
As simple as the title. My images are working on desktop, android, but not iPhone Safari

```
    "webpack": "^4.23.1",
    "image-webpack-loader": "^4.4.0",
```

**Comment by ksnyde** [comment]
I’d be willing to bet this has NOTHING to do with this module. Can you open the image in desktop Safari via the file menu? If yes then I’m 100% certain there is no issue with this module.

**Comment by SeedyROM** [comment]
## This should be reopened

To all who find this! This is caused by having the `webp` setting in your `image-webpack-loader` options set.

*The issue came from a Windows 10 environment, but I will test this tomorrow on Ubuntu.*

A colleague of mine was having this issue on iOS, fortunately for them I have some knowledge of how file formats are stored at the binary level. So after some inspection with a hex editor we discovered this had been causing the plugin to convert **everything** to webp, without changing the extensions accordingly. This can be seen in this screenshot of a .jpg file:

![Hex Editor Output](https://gyazo.com/e0a98025fa0748c49cfed4e36cbc9f52)

The first few bytes in ascii are RIFF, which the iOS image parsing tools simply find invalid since the extension doesn't match. This also happens with any other valid image format.

It seems most browsers and Android simply read the header marker of the file and ignore the extension entirely.

It should also be noted that file upload websites would find the files invalid as well since they don't support WebP, this was where our initial aha moment was.

![Error](https://gyazo.com/e0a98025fa0748c49cfed4e36cbc9f52)

So **yes** this is a notable configuration bug, since it's fairly undocumented/unnoticed from what I've seen.

**Comment by Sunhat** [comment]
This was a long time ago on at a previous company I was working for, but I do recall I was working on macOS
