### ISSUE TITLE
imagemin-pngquant  installed failed

### ISSUE THREAD

**Issue by wuyingreng** [imagemin/imagemin#336]
when use loader: "image-webpack-loader",it remind Cannot find module 'imagemin-pngquant'.And I install imagemin-pngquant ,it installed failed.Error: pngquant failed to build, make sure that libpng-dev is installed.Here is my log.Thanks
[2019-10-15T10_08_19_225Z-debug.log](https://github.com/imagemin/imagemin/files/3728642/2019-10-15T10_08_19_225Z-debug.log)
[2019-10-15T10_02_18_092Z-debug.log](https://github.com/imagemin/imagemin/files/3728643/2019-10-15T10_02_18_092Z-debug.log)

**Comment by 1000ch** [comment]
This should be issued on [imagemin/imagemin-pngquant/issues](https://github.com/imagemin/imagemin-pngquant/issues) because this might not be a problem of imagemin itself.

Anyway, [pngquant-bin requires some dependencies](https://github.com/imagemin/pngquant-bin#updating-pre-compiled-binaries). Would you try to install again with referring that instruction?
